name: Pyinstaller

on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'src/app.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'parqet_to_pp_converter'
          options: --onefile, --name "parqet_to_pp_converter", --windowed, --add-data "src/templates;src/templates", --add-data "src/static;src/static", --hidden-import=flask, --icon=src/csv_converter_logo.ico
