name: Pyinstaller

on: [push]

jobs:
  pyinstaller-build:
    runs-on: <windows-latest>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/app.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'parqet_to_pp_converter'
          options: --onefile, --name "parqet_to_pp_converter", --windowed, --add-data "templates;templates", --add-data "static;static", --hidden-import=flask, --icon=csv_converter_logo.ico
